### ISSUE TITLE
2024: Consider deprecating MicroProfile Context Propagation

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-wg#234]
Consider deprecating MicroProfile Context Propagation: Nathan,

**Comment by Emily-Jiang** [comment]
Nathan: enough functionalities have been moved to Jakarta Concurrency. The context propagation for CDI, Tx would not be moved to Jakarta because CDI and Tx have not agreed to take it on.

**Comment by njr-11** [comment]
Some background that was requested on the MicroProfile Community Call:

MicroProfile Context Propagation was created to innovate in the Java EE Concurrency space while the Java EE was locked down. The specification was created with the stated intent of eventually contributing it to Java EE Concurrency.  Java EE was replaced by Jakarta EE, and in the first release of Jakarta EE that allowed updates other than javax-to-jakarta package renames, the majority of the MicroProfile Context Propagation specification and API was contributed to the Jakarta Concurrency (3.0) specification. Since then, development of the technology has continued within the Jakarta Concurrency specification and not the MicroProfile Context Propagation specification.

Also, on the 2024/04/16 MicroProfile Community Call, RedHat representatives have confirmed that they do not need the remaining portions of MicroProfile Context Propagation added to Jakarta Concurrency.

**Comment by Emily-Jiang** [comment]
Update Readme doc to the status: with the following:
_status: discontinued (this specification has been replaced by Jakarta Concurrency.)_

**Comment by Emily-Jiang** [comment]
done with [this](https://github.com/eclipse/microprofile-context-propagation/pull/220) PR
